apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplifier-designtime-pvc
  namespace: simplifier
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

# internal akka cluster usage
apiVersion: v1
kind: Service
metadata:
  name: simplifier-designtime
  namespace: simplifier
spec:
  selector:
    app: simplifier-designtime
  clusterIP: None
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simplifier-designtime
  namespace: simplifier
spec:
  serviceName: simplifier-designtime
  selector:
    matchLabels:
      app: simplifier-designtime
  replicas: 1
  template:
    metadata:
      labels:
        app: simplifier-designtime
    spec:
      containers:
        - image: simplifierag/workflow-designtime:8.1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "0.5"
          name: simplifier-designtime
          env:
            - name: SECOND_SEED
              value: simplifier-launchpad
            - name: MODULE_HOST
              value: simplifier-designtime
            - name: SIMPLIFIER_HOST
              value: simplifier
            - name: JVM_ARGS
              valueFrom:
                configMapKeyRef:
                  name: simplifier-config
                  key: WF_DT_JVM_HEAP_GB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: simplifier-secrets
                  key: MYSQL_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: simplifier-secrets
                  key: SIMPLIFIER_PW
            - name: DB_DATABASE
              value: simplifier_wf_dt
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: simplifier-config
                  key: MYSQL_PORT
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: simplifier-config
                  key: TZ
          volumeMounts:
            - name: simplifier-designtime-storage
              mountPath: /home/workflowDesigntime/data
      volumes:
        - name: simplifier-designtime-storage
          persistentVolumeClaim:
            claimName: simplifier-designtime-pvc
