apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: simplifier
spec:
  dataSource:
    name: snapshot-mysql
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplifier-pvc
  namespace: simplifier
spec:
  dataSource:
    name: snapshot-simplifier
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplifier-launchpad-pvc
  namespace: simplifier
spec:
  dataSource:
    name: snapshot-simplifier-launchpad
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplifier-designtime-pvc
  namespace: simplifier
spec:
  dataSource:
    name: snapshot-simplifier-designtime
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplifier-runtime-pvc
  namespace: simplifier
spec:
  dataSource:
    name: snapshot-simplifier-runtime
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi