#source
#https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: simplifier
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: simplifier
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        args: ["--max_allowed_packet=1073741824", "--wait_timeout=28800", "--default-authentication-plugin=caching_sha2_password", "--log_bin_trust_function_creators=1"]
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: simplifier-secrets
              key: MYSQL_ROOT_PW
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: simplifier
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: simplifier
spec:
  storageClassName: manual
  volumeName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi